// eslint-disable-next-line no-shadow
export enum Icon {
  ColorfulAlpha = 'colorful--alpha',
  ColorfulAssetBaa = 'colorful--asset-baa',
  ColorfulAssetBoa = 'colorful--asset-boa',
  ColorfulAssetBrf = 'colorful--asset-brf',
  ColorfulAssetFba = 'colorful--asset-fba',
  ColorfulAssetSba = 'colorful--asset-sba',
  ColorfulAssetUsd = 'colorful--asset-usd',
  ColorfulAssetVault = 'colorful--asset-vault',
  ColorfulBitcoinFont = 'colorful--bitcoin-font',
  ColorfulBitcoinFull = 'colorful--bitcoin-full',
  ColorfulBitcoin = 'colorful--bitcoin',
  ColorfulBtcDarkLogo = 'colorful--btc-dark-logo',
  ColorfulBtcLightning = 'colorful--btc-lightning',
  ColorfulCamera = 'colorful--camera',
  ColorfulComment = 'colorful--comment',
  ColorfulCopy = 'colorful--copy',
  ColorfulFacebookCircle = 'colorful--facebook-circle',
  ColorfulFacebook = 'colorful--facebook',
  ColorfulFk = 'colorful--fk',
  ColorfulFlagsAu = 'colorful--flags--au',
  ColorfulFlagsRu = 'colorful--flags--ru',
  ColorfulFolder = 'colorful--folder',
  ColorfulGooglePay = 'colorful--google-pay',
  ColorfulGoogle = 'colorful--google',
  ColorfulLandingshield = 'colorful--landingshield',
  ColorfulLandingtimer = 'colorful--landingtimer',
  ColorfulLangindrocket = 'colorful--langindrocket',
  ColorfulLogoWhite = 'colorful--logo-white',
  ColorfulMailShiny = 'colorful--mail-shiny',
  ColorfulMail = 'colorful--mail',
  ColorfulMastercard = 'colorful--mastercard',
  ColorfulMetamask = 'colorful--metamask',
  ColorfulMir = 'colorful--mir',
  ColorfulPiastrix = 'colorful--piastrix',
  ColorfulRaiffeisen = 'colorful--raiffeisen',
  ColorfulSber = 'colorful--sber',
  ColorfulSbp = 'colorful--sbp',
  ColorfulStarHalf = 'colorful--star-half',
  ColorfulStar = 'colorful--star',
  ColorfulTelegram = 'colorful--telegram',
  ColorfulTelegram2 = 'colorful--telegram2',
  ColorfulTinkoff = 'colorful--tinkoff',
  ColorfulTron = 'colorful--tron',
  ColorfulTwitter = 'colorful--twitter',
  ColorfulUsdant = 'colorful--usdant',
  ColorfulUsdtTrc20 = 'colorful--usdt-trc20',
  ColorfulUsdt = 'colorful--usdt',
  ColorfulUsdttron = 'colorful--usdttron',
  ColorfulVisa = 'colorful--visa',
  ColorfulVisawhite = 'colorful--visawhite',
  ColorfulVk = 'colorful--vk',
  ColorfulVtb = 'colorful--vtb',
  ColorfulWalletConnect = 'colorful--walletConnect',
  ColorfulWhatsApp = 'colorful--whatsApp',
  ColorfulYoomoney = 'colorful--yoomoney',
  MonoActionCheckMark = 'mono--action--check-mark',
  MonoActionClose = 'mono--action--close',
  MonoActionCross = 'mono--action--cross',
  MonoActionEdit = 'mono--action--edit',
  MonoActionFavoriteFilled = 'mono--action--favorite-filled',
  MonoActionFavorite = 'mono--action--favorite',
  MonoActionFilter = 'mono--action--filter',
  MonoActionMaximize = 'mono--action--maximize',
  MonoActionMenu = 'mono--action--menu',
  MonoActionMinimize = 'mono--action--minimize',
  MonoActionMore = 'mono--action--more',
  MonoActionPlayFilled = 'mono--action--play-filled',
  MonoActionPlayOutline = 'mono--action--play-outline',
  MonoActionPlay = 'mono--action--play',
  MonoActionPlayerPause = 'mono--action--player-pause',
  MonoActionPlus = 'mono--action--plus',
  MonoActionProgram = 'mono--action--program',
  MonoActionResizer = 'mono--action--resizer',
  MonoActionSettings = 'mono--action--settings',
  MonoActionShareArrow = 'mono--action--share-arrow',
  MonoActionShare = 'mono--action--share',
  MonoActionSkipLeft = 'mono--action--skip-left',
  MonoActionSkipRight = 'mono--action--skip-right',
  MonoActionSort = 'mono--action--sort',
  MonoActionTrash = 'mono--action--trash',
  MonoActionVolumeOff = 'mono--action--volume-off',
  MonoActionVolumeOn = 'mono--action--volume-on',
  MonoActionWatchNext = 'mono--action--watch-next',
  MonoAnalytics = 'mono--analytics',
  MonoApplePay = 'mono--apple-pay',
  MonoApple = 'mono--apple',
  MonoBit = 'mono--bit',
  MonoBitcoinB = 'mono--bitcoin-b',
  MonoBlog = 'mono--blog',
  MonoBtcUni = 'mono--btc-uni',
  MonoChevronBottom = 'mono--chevron-bottom',
  MonoChevronLeft = 'mono--chevron-left',
  MonoChevronLightBottom = 'mono--chevron-light-bottom',
  MonoChevronRight = 'mono--chevron-right',
  MonoChevronTop = 'mono--chevron-top',
  MonoCopy = 'mono--copy',
  MonoCreditCard = 'mono--credit-card',
  MonoEarnings = 'mono--earnings',
  MonoEyeCrossed = 'mono--eye-crossed',
  MonoEye = 'mono--eye',
  MonoFacebookBlack = 'mono--facebook-black',
  MonoFacebook = 'mono--facebook',
  MonoFile = 'mono--file',
  MonoInfo = 'mono--info',
  MonoInstagramBlack = 'mono--instagram-black',
  MonoLearn = 'mono--learn',
  MonoLink = 'mono--link',
  MonoLinkedinBlack = 'mono--linkedin-black',
  MonoLock = 'mono--lock',
  MonoLogout = 'mono--logout',
  MonoMailLight = 'mono--mail-light',
  MonoMail = 'mono--mail',
  MonoMedium = 'mono--medium',
  MonoMenu = 'mono--menu',
  MonoMessage = 'mono--message',
  MonoMinus = 'mono--minus',
  MonoMore = 'mono--more',
  MonoNavigationArrowBottom = 'mono--navigation--arrow-bottom',
  MonoNavigationArrowLeftWhite = 'mono--navigation--arrow-left-white',
  MonoNavigationArrowLeft = 'mono--navigation--arrow-left',
  MonoNavigationArrowRight = 'mono--navigation--arrow-right',
  MonoNavigationArrowTop = 'mono--navigation--arrow-top',
  MonoNavigationChevronBottom = 'mono--navigation--chevron-bottom',
  MonoNavigationChevronLeft = 'mono--navigation--chevron-left',
  MonoNavigationChevronRight = 'mono--navigation--chevron-right',
  MonoNavigationChevronTop = 'mono--navigation--chevron-top',
  MonoNavigationDownloadOrder = 'mono--navigation--download-order',
  MonoNavigationDownloadPause = 'mono--navigation--download-pause',
  MonoNavigationDownloadStoped = 'mono--navigation--download-stoped',
  MonoNavigationDownload = 'mono--navigation--download',
  MonoNavigationDownloaded = 'mono--navigation--downloaded',
  MonoNavigationItems = 'mono--navigation--items',
  MonoNavigationLoader = 'mono--navigation--loader',
  MonoNavigationLogout = 'mono--navigation--logout',
  MonoNavigationSearch = 'mono--navigation--search',
  MonoNavigationUser = 'mono--navigation--user',
  MonoPaste = 'mono--paste',
  MonoPlus = 'mono--plus',
  MonoProfile = 'mono--profile',
  MonoSatoshiUni = 'mono--satoshi-uni',
  MonoSupport = 'mono--support',
  MonoTelegramBlack = 'mono--telegram-black',
  MonoTelegram = 'mono--telegram',
  MonoTelegram2Black = 'mono--telegram2-black',
  MonoTerms = 'mono--terms',
  MonoTheme = 'mono--theme',
  MonoTwitterBlack = 'mono--twitter-black',
  MonoTwitter = 'mono--twitter',
  MonoUnknownBlack = 'mono--unknown-black',
  MonoVk = 'mono--vk',
  MonoWallet = 'mono--wallet',
  MonoWithdraw = 'mono--withdraw',
  MonoX = 'mono--x',
  MonoMoney = 'mono--money',
}
export const files = {
  [Icon.ColorfulAlpha]: '/img/icons/colorful/alpha.svg',
  [Icon.ColorfulAssetBaa]: '/img/icons/colorful/asset-baa.svg',
  [Icon.ColorfulAssetBoa]: '/img/icons/colorful/asset-boa.svg',
  [Icon.ColorfulAssetBrf]: '/img/icons/colorful/asset-brf.svg',
  [Icon.ColorfulAssetFba]: '/img/icons/colorful/asset-fba.svg',
  [Icon.ColorfulAssetSba]: '/img/icons/colorful/asset-sba.svg',
  [Icon.ColorfulAssetUsd]: '/img/icons/colorful/asset-usd.svg',
  [Icon.ColorfulAssetVault]: '/img/icons/colorful/asset-vault.svg',
  [Icon.ColorfulBitcoinFont]: '/img/icons/colorful/bitcoin-font.svg',
  [Icon.ColorfulBitcoinFull]: '/img/icons/colorful/bitcoin-full.svg',
  [Icon.ColorfulBitcoin]: '/img/icons/colorful/bitcoin.svg',
  [Icon.ColorfulBtcDarkLogo]: '/img/icons/colorful/btc-dark-logo.svg',
  [Icon.ColorfulBtcLightning]: '/img/icons/colorful/btc-lightning.svg',
  [Icon.ColorfulCamera]: '/img/icons/colorful/camera.svg',
  [Icon.ColorfulComment]: '/img/icons/colorful/comment.svg',
  [Icon.ColorfulCopy]: '/img/icons/colorful/copy.svg',
  [Icon.ColorfulFacebookCircle]: '/img/icons/colorful/facebook-circle.svg',
  [Icon.ColorfulFacebook]: '/img/icons/colorful/facebook.svg',
  [Icon.ColorfulFk]: '/img/icons/colorful/fk.svg',
  [Icon.ColorfulFlagsAu]: '/img/icons/colorful/flags/au.svg',
  [Icon.ColorfulFlagsRu]: '/img/icons/colorful/flags/ru.svg',
  [Icon.ColorfulFolder]: '/img/icons/colorful/folder.svg',
  [Icon.ColorfulGooglePay]: '/img/icons/colorful/google-pay.svg',
  [Icon.ColorfulGoogle]: '/img/icons/colorful/google.svg',
  [Icon.ColorfulLandingshield]: '/img/icons/colorful/landingshield.svg',
  [Icon.ColorfulLandingtimer]: '/img/icons/colorful/landingtimer.svg',
  [Icon.ColorfulLangindrocket]: '/img/icons/colorful/langindrocket.svg',
  [Icon.ColorfulLogoWhite]: '/img/icons/colorful/logo-white.svg',
  [Icon.ColorfulMailShiny]: '/img/icons/colorful/mail-shiny.svg',
  [Icon.ColorfulMail]: '/img/icons/colorful/mail.svg',
  [Icon.ColorfulMastercard]: '/img/icons/colorful/mastercard.svg',
  [Icon.ColorfulMetamask]: '/img/icons/colorful/metamask.svg',
  [Icon.ColorfulMir]: '/img/icons/colorful/mir.svg',
  [Icon.ColorfulPiastrix]: '/img/icons/colorful/piastrix.svg',
  [Icon.ColorfulRaiffeisen]: '/img/icons/colorful/raiffeisen.svg',
  [Icon.ColorfulSber]: '/img/icons/colorful/sber.svg',
  [Icon.ColorfulSbp]: '/img/icons/colorful/sbp.svg',
  [Icon.ColorfulStarHalf]: '/img/icons/colorful/star-half.svg',
  [Icon.ColorfulStar]: '/img/icons/colorful/star.svg',
  [Icon.ColorfulTelegram]: '/img/icons/colorful/telegram.svg',
  [Icon.ColorfulTelegram2]: '/img/icons/colorful/telegram2.svg',
  [Icon.ColorfulTinkoff]: '/img/icons/colorful/tinkoff.svg',
  [Icon.ColorfulTron]: '/img/icons/colorful/tron.svg',
  [Icon.ColorfulTwitter]: '/img/icons/colorful/twitter.svg',
  [Icon.ColorfulUsdant]: '/img/icons/colorful/usdant.svg',
  [Icon.ColorfulUsdtTrc20]: '/img/icons/colorful/usdt-trc20.svg',
  [Icon.ColorfulUsdt]: '/img/icons/colorful/usdt.svg',
  [Icon.ColorfulUsdttron]: '/img/icons/colorful/usdttron.svg',
  [Icon.ColorfulVisa]: '/img/icons/colorful/visa.svg',
  [Icon.ColorfulVisawhite]: '/img/icons/colorful/visawhite.svg',
  [Icon.ColorfulVk]: '/img/icons/colorful/vk.svg',
  [Icon.ColorfulVtb]: '/img/icons/colorful/vtb.svg',
  [Icon.ColorfulWalletConnect]: '/img/icons/colorful/walletConnect.svg',
  [Icon.ColorfulWhatsApp]: '/img/icons/colorful/whatsApp.svg',
  [Icon.ColorfulYoomoney]: '/img/icons/colorful/yoomoney.svg',
  [Icon.MonoActionCheckMark]: '/img/icons/mono/action/check-mark.svg',
  [Icon.MonoActionClose]: '/img/icons/mono/action/close.svg',
  [Icon.MonoActionCross]: '/img/icons/mono/action/cross.svg',
  [Icon.MonoActionEdit]: '/img/icons/mono/action/edit.svg',
  [Icon.MonoActionFavoriteFilled]: '/img/icons/mono/action/favorite-filled.svg',
  [Icon.MonoActionFavorite]: '/img/icons/mono/action/favorite.svg',
  [Icon.MonoActionFilter]: '/img/icons/mono/action/filter.svg',
  [Icon.MonoActionMaximize]: '/img/icons/mono/action/maximize.svg',
  [Icon.MonoActionMenu]: '/img/icons/mono/action/menu.svg',
  [Icon.MonoActionMinimize]: '/img/icons/mono/action/minimize.svg',
  [Icon.MonoActionMore]: '/img/icons/mono/action/more.svg',
  [Icon.MonoActionPlayFilled]: '/img/icons/mono/action/play-filled.svg',
  [Icon.MonoActionPlayOutline]: '/img/icons/mono/action/play-outline.svg',
  [Icon.MonoActionPlay]: '/img/icons/mono/action/play.svg',
  [Icon.MonoActionPlayerPause]: '/img/icons/mono/action/player-pause.svg',
  [Icon.MonoActionPlus]: '/img/icons/mono/action/plus.svg',
  [Icon.MonoActionProgram]: '/img/icons/mono/action/program.svg',
  [Icon.MonoActionResizer]: '/img/icons/mono/action/resizer.svg',
  [Icon.MonoActionSettings]: '/img/icons/mono/action/settings.svg',
  [Icon.MonoActionShareArrow]: '/img/icons/mono/action/share-arrow.svg',
  [Icon.MonoActionShare]: '/img/icons/mono/action/share.svg',
  [Icon.MonoActionSkipLeft]: '/img/icons/mono/action/skip-left.svg',
  [Icon.MonoActionSkipRight]: '/img/icons/mono/action/skip-right.svg',
  [Icon.MonoActionSort]: '/img/icons/mono/action/sort.svg',
  [Icon.MonoActionTrash]: '/img/icons/mono/action/trash.svg',
  [Icon.MonoActionVolumeOff]: '/img/icons/mono/action/volume-off.svg',
  [Icon.MonoActionVolumeOn]: '/img/icons/mono/action/volume-on.svg',
  [Icon.MonoActionWatchNext]: '/img/icons/mono/action/watch-next.svg',
  [Icon.MonoAnalytics]: '/img/icons/mono/analytics.svg',
  [Icon.MonoApplePay]: '/img/icons/mono/apple-pay.svg',
  [Icon.MonoApple]: '/img/icons/mono/apple.svg',
  [Icon.MonoBit]: '/img/icons/mono/bit.svg',
  [Icon.MonoBitcoinB]: '/img/icons/mono/bitcoin-b.svg',
  [Icon.MonoBlog]: '/img/icons/mono/blog.svg',
  [Icon.MonoBtcUni]: '/img/icons/mono/btc-uni.svg',
  [Icon.MonoChevronBottom]: '/img/icons/mono/chevron-bottom.svg',
  [Icon.MonoChevronLeft]: '/img/icons/mono/chevron-left.svg',
  [Icon.MonoChevronLightBottom]: '/img/icons/mono/chevron-light-bottom.svg',
  [Icon.MonoChevronRight]: '/img/icons/mono/chevron-right.svg',
  [Icon.MonoChevronTop]: '/img/icons/mono/chevron-top.svg',
  [Icon.MonoCopy]: '/img/icons/mono/copy.svg',
  [Icon.MonoCreditCard]: '/img/icons/mono/credit-card.svg',
  [Icon.MonoEarnings]: '/img/icons/mono/earnings.svg',
  [Icon.MonoEyeCrossed]: '/img/icons/mono/eye-crossed.svg',
  [Icon.MonoEye]: '/img/icons/mono/eye.svg',
  [Icon.MonoFacebookBlack]: '/img/icons/mono/facebook-black.svg',
  [Icon.MonoFacebook]: '/img/icons/mono/facebook.svg',
  [Icon.MonoFile]: '/img/icons/mono/file.svg',
  [Icon.MonoInfo]: '/img/icons/mono/info.svg',
  [Icon.MonoInstagramBlack]: '/img/icons/mono/instagram-black.svg',
  [Icon.MonoLearn]: '/img/icons/mono/learn.svg',
  [Icon.MonoLink]: '/img/icons/mono/link.svg',
  [Icon.MonoLinkedinBlack]: '/img/icons/mono/linkedin-black.svg',
  [Icon.MonoLock]: '/img/icons/mono/lock.svg',
  [Icon.MonoLogout]: '/img/icons/mono/logout.svg',
  [Icon.MonoMailLight]: '/img/icons/mono/mail-light.svg',
  [Icon.MonoMail]: '/img/icons/mono/mail.svg',
  [Icon.MonoMedium]: '/img/icons/mono/medium.svg',
  [Icon.MonoMenu]: '/img/icons/mono/menu.svg',
  [Icon.MonoMessage]: '/img/icons/mono/message.svg',
  [Icon.MonoMinus]: '/img/icons/mono/minus.svg',
  [Icon.MonoMore]: '/img/icons/mono/more.svg',
  [Icon.MonoNavigationArrowBottom]: '/img/icons/mono/navigation/arrow-bottom.svg',
  [Icon.MonoNavigationArrowLeftWhite]: '/img/icons/mono/navigation/arrow-left-white.svg',
  [Icon.MonoNavigationArrowLeft]: '/img/icons/mono/navigation/arrow-left.svg',
  [Icon.MonoNavigationArrowRight]: '/img/icons/mono/navigation/arrow-right.svg',
  [Icon.MonoNavigationArrowTop]: '/img/icons/mono/navigation/arrow-top.svg',
  [Icon.MonoNavigationChevronBottom]: '/img/icons/mono/navigation/chevron-bottom.svg',
  [Icon.MonoNavigationChevronLeft]: '/img/icons/mono/navigation/chevron-left.svg',
  [Icon.MonoNavigationChevronRight]: '/img/icons/mono/navigation/chevron-right.svg',
  [Icon.MonoNavigationChevronTop]: '/img/icons/mono/navigation/chevron-top.svg',
  [Icon.MonoNavigationDownloadOrder]: '/img/icons/mono/navigation/download-order.svg',
  [Icon.MonoNavigationDownloadPause]: '/img/icons/mono/navigation/download-pause.svg',
  [Icon.MonoNavigationDownloadStoped]: '/img/icons/mono/navigation/download-stoped.svg',
  [Icon.MonoNavigationDownload]: '/img/icons/mono/navigation/download.svg',
  [Icon.MonoNavigationDownloaded]: '/img/icons/mono/navigation/downloaded.svg',
  [Icon.MonoNavigationItems]: '/img/icons/mono/navigation/items.svg',
  [Icon.MonoNavigationLoader]: '/img/icons/mono/navigation/loader.svg',
  [Icon.MonoNavigationLogout]: '/img/icons/mono/navigation/logout.svg',
  [Icon.MonoNavigationSearch]: '/img/icons/mono/navigation/search.svg',
  [Icon.MonoNavigationUser]: '/img/icons/mono/navigation/user.svg',
  [Icon.MonoPaste]: '/img/icons/mono/paste.svg',
  [Icon.MonoPlus]: '/img/icons/mono/plus.svg',
  [Icon.MonoProfile]: '/img/icons/mono/profile.svg',
  [Icon.MonoSatoshiUni]: '/img/icons/mono/satoshi-uni.svg',
  [Icon.MonoSupport]: '/img/icons/mono/support.svg',
  [Icon.MonoTelegramBlack]: '/img/icons/mono/telegram-black.svg',
  [Icon.MonoTelegram]: '/img/icons/mono/telegram.svg',
  [Icon.MonoTelegram2Black]: '/img/icons/mono/telegram2-black.svg',
  [Icon.MonoTerms]: '/img/icons/mono/terms.svg',
  [Icon.MonoTheme]: '/img/icons/mono/theme.svg',
  [Icon.MonoTwitterBlack]: '/img/icons/mono/twitter-black.svg',
  [Icon.MonoTwitter]: '/img/icons/mono/twitter.svg',
  [Icon.MonoUnknownBlack]: '/img/icons/mono/unknown-black.svg',
  [Icon.MonoVk]: '/img/icons/mono/vk.svg',
  [Icon.MonoWallet]: '/img/icons/mono/wallet.svg',
  [Icon.MonoWithdraw]: '/img/icons/mono/withdraw.svg',
  [Icon.MonoX]: '/img/icons/mono/x.svg',
  [Icon.MonoMoney]: '/img/icons/mono/money.svg',
}
