{{- if or (eq .Values.global.env_name "dev") (eq .Values.global.env_name "stage") }}
apiVersion: v1
kind: Secret
metadata:
  name: basic-auth-new
type: Opaque
data:
  auth: Z3Vlc3Q6JGFwcjEkNXkvQkR1QUQka0VQa1JjWU5Pakp3OXkzS0g2OFU0Lw==
{{- end }}
