{{- $globals := ternary .Values.global.stage (ternary .Values.global.prod .Values.global.dev (eq .Values.global.env_name "prod")) (eq .Values.global.env_name "stage") -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-1
data:
  {{- (.Files.Glob "conf/nginx/*").AsConfig | nindent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-2
data:
  {{- (.Files.Glob "conf/nginx/conf.d/*").AsConfig | nindent 2 }}
---
