{{- $ci_path := printf "/%s" ((default "/" .Values.global.ci_path) | trim | trimAll "/") -}}
{{- $globals := ternary .Values.global.stage (ternary .Values.global.prod .Values.global.dev (eq .Values.global.env_name "prod")) (eq .Values.global.env_name "stage") -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    cert-manager.io/issuer: prod-issuer
    cert-manager.io/issuer-group: cert-manager.k8s.cloudflare.com
    cert-manager.io/issuer-kind: OriginIssuer
    cert-manager.io/private-key-rotation-policy: "Always"
    nginx.ingress.kubernetes.io/from-to-www-redirect: 'true'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    {{- if or (eq .Values.global.env_name "stage") (eq .Values.global.env_name "dev") }}
    nginx.ingress.kubernetes.io/auth-realm: Authentication Required
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-type: basic
    {{- end }}
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ .Values.global.ci_url }}
    - {{ .Values.global.app_url }}
    secretName: tls-secret-{{ .Values.global.app_name }}
  rules:
  - host: {{ .Values.global.ci_url }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: {{ .Values.global.app_name }}
            port:
              name: http
  - host: {{ .Values.global.app_url }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: {{ .Values.global.app_name }}
            port:
              name: http